#pragma once
#include <bgfx/bgfx.h>
#include <cstdint>
#include <memory>
#include "../grx_common/IExecutive.h"
#include "../gx_render/RenderDevice.h"
#include "../gx_render/TextureManager.h"
#include "../gx_render/Shader.h"

class ExecutiveImpl : public I4DyuchiGXExecutive {
public:
    ExecutiveImpl();
    virtual ~ExecutiveImpl();

    STDMETHODIMP QueryInterface(REFIID, PPVOID);
    STDMETHODIMP_(ULONG) AddRef(void);
    STDMETHODIMP_(ULONG) Release(void);

    I4DyuchiGXRenderer* __stdcall GetRenderer();
    I4DyuchiGXGeometry* __stdcall GetGeometry();
    HRESULT __stdcall GetRenderer(I4DyuchiGXRenderer**);
    HRESULT __stdcall GetGeometry(I4DyuchiGXGeometry**);
    HRESULT __stdcall GetFileStorage(I4DyuchiFileStorage**);
    BOOL __stdcall InitializeWithoutRegistry(char*, char*, HWND, DISPLAY_INFO*, DWORD, DWORD, DWORD, DWORD, DWORD, ErrorHandleProc);
    BOOL __stdcall Initialize(HWND, DISPLAY_INFO*, DWORD, DWORD, DWORD, DWORD, DWORD, ErrorHandleProc);
    BOOL __stdcall InitializeFileStorageWithoutRegistry(char*, DWORD, DWORD, DWORD, FILE_ACCESS_METHOD, PACKFILE_NAME_TABLE*, DWORD, BOOL);
    BOOL __stdcall InitializeFileStorage(DWORD, DWORD, DWORD, FILE_ACCESS_METHOD, PACKFILE_NAME_TABLE*, DWORD, BOOL);
    void __stdcall SetViewport(DWORD);
    DWORD __stdcall IsValidHandle(GXMAP_OBJECT_HANDLE);
    DWORD __stdcall GXOProcess(GXOBJECT_HANDLE, DWORD);
    BOOL __stdcall GXORender(GXOBJECT_HANDLE);
    void __stdcall GXOSetCurrentFrame(GXOBJECT_HANDLE, DWORD);
    void __stdcall GXOSetCurrentMotionIndex(GXOBJECT_HANDLE, DWORD);
    BOOL __stdcall GXOGetMotionDesc(GXOBJECT_HANDLE, MOTION_DESC*, DWORD, DWORD);
    DWORD __stdcall GXOGetMotionNum(GXOBJECT_HANDLE, DWORD);
    DWORD __stdcall GXOGetCurrentFrame(GXOBJECT_HANDLE);
    DWORD __stdcall GXOGetCurrentMotionIndex(GXOBJECT_HANDLE);
    void __stdcall GXOSetCurrentMaterialIndex(GXOBJECT_HANDLE, DWORD);
    DWORD __stdcall GXOGetMaterialNum(GXOBJECT_HANDLE, DWORD);
    DWORD __stdcall GXOGetCurrentMaterialIndex(GXOBJECT_HANDLE);
    void __stdcall GXOSetPosition(GXOBJECT_HANDLE, VECTOR3*, BOOL);
    void __stdcall GXOMovePosition(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOGetPosition(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOMovePositionWithCollide(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOGetInterpolatedPosition(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOSetDirection(GXOBJECT_HANDLE, VECTOR3*, float);
    void __stdcall GXOSetDirectionFPSStyle(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOChangeDirection(GXOBJECT_HANDLE, float);
    void __stdcall GXOGetDirection(GXOBJECT_HANDLE, VECTOR3*, float*);
    void __stdcall GXOGetDirectionFPSStyle(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOSetScale(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOGetScale(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOMoveForward(GXOBJECT_HANDLE, float);
    void __stdcall GXOEnableHFieldApply(GXOBJECT_HANDLE);
    void __stdcall GXODisableHFieldApply(GXOBJECT_HANDLE);
    BOOL __stdcall GXOIsHFieldApply(GXOBJECT_HANDLE);
    void __stdcall GXOEnableAsEffect(GXOBJECT_HANDLE);
    void __stdcall GXODisableAsEffect(GXOBJECT_HANDLE);
    BOOL __stdcall GXOIsAsEffect(GXOBJECT_HANDLE);
    BOOL __stdcall GXOIsLanding(GXOBJECT_HANDLE);
    void __stdcall GXOSetZOrder(GXOBJECT_HANDLE, int);
    void __stdcall GXOEnableSelfIllumin(GXOBJECT_HANDLE);
    void __stdcall GXODisableSelfIllumin(GXOBJECT_HANDLE);
    BOOL __stdcall GXOIsEnableSelfIllumin(GXOBJECT_HANDLE);
    void __stdcall EstimatedMoveForward(GXOBJECT_HANDLE, VECTOR3*, float);
    BOOL __stdcall GXOAttach(GXOBJECT_HANDLE, GXOBJECT_HANDLE, char*);
    BOOL __stdcall GXOAttachWithModelIndex(GXOBJECT_HANDLE, GXOBJECT_HANDLE, DWORD, char*);
    BOOL __stdcall GXODetach(GXOBJECT_HANDLE, GXOBJECT_HANDLE);
    BOOL __stdcall GXOAttachLight(GXOBJECT_HANDLE, char*, GXLIGHT_HANDLE, VECTOR3*, DWORD);
    BOOL __stdcall GXODetachLight(GXOBJECT_HANDLE, GXLIGHT_HANDLE);
    BOOL __stdcall GXOAttachCameraFront(GXOBJECT_HANDLE, float);
    BOOL __stdcall GXODetachCameraFront(GXOBJECT_HANDLE);
    ULONG __stdcall GXOGetModel(GXOBJECT_HANDLE, I3DModel**, DWORD*, DWORD);
    GXOBJECT_HANDLE __stdcall GXOGetObjectWithScreenCoord(VECTOR3*, DWORD*, DWORD*, float*, POINT*, DWORD, DWORD);
    DWORD __stdcall GXOGetMultipleObjectWithScreenCoordRect(PICK_GXOBJECT_DESC*, DWORD, RECT*, DWORD, DWORD);
    DWORD __stdcall GXOGetMultipleObjectWithScreenCoord(PICK_GXOBJECT_DESC*, DWORD, POINT*, DWORD, DWORD);
    BOOL __stdcall GXOReplaceModel(GXOBJECT_HANDLE, DWORD, char*);
    void __stdcall GXOGetCollisionMesh(GXOBJECT_HANDLE, COLLISION_MESH_OBJECT_DESC*);
    DWORD __stdcall GXOGetObjectIndex(GXOBJECT_HANDLE, char*, DWORD);
    BOOL __stdcall GXOGetWorldMatrixPerObject(GXOBJECT_HANDLE, MATRIX4*, DWORD, DWORD);
    DWORD __stdcall GXOGetAllObjectsWitLoadMapScript(GXOBJECT_HANDLE*, DWORD);
    void __stdcall DisableRender(GXMAP_OBJECT_HANDLE);
    void __stdcall EnableRender(GXMAP_OBJECT_HANDLE);
    void __stdcall DisableSchedule(GXMAP_OBJECT_HANDLE);
    void __stdcall EnableSchedule(GXMAP_OBJECT_HANDLE);
    BOOL __stdcall IsRenderable(GXMAP_OBJECT_HANDLE);
    void __stdcall SetPickType(GXMAP_OBJECT_HANDLE, PICK_TYPE);
    PICK_TYPE __stdcall GetPickType(GXMAP_OBJECT_HANDLE);
    void __stdcall SetRenderFlag(GXMAP_OBJECT_HANDLE, DWORD);
    DWORD __stdcall GetRenderFlag(GXMAP_OBJECT_HANDLE);
    void __stdcall SetAlphaFlag(GXMAP_OBJECT_HANDLE, DWORD);
    DWORD __stdcall GetAlphaFlag(GXMAP_OBJECT_HANDLE);
    void* __stdcall GetData(GXMAP_OBJECT_HANDLE);
    void __stdcall SetData(GXMAP_OBJECT_HANDLE, void*);
    DWORD __stdcall GetID(GXMAP_OBJECT_HANDLE);
    BOOL __stdcall SetID(GXMAP_OBJECT_HANDLE, DWORD);
    void __stdcall ReleaseID(GXMAP_OBJECT_HANDLE);
    GXMAP_OBJECT_HANDLE __stdcall GetGXMapObjectWithID(DWORD);
    void __stdcall SetPropertyFlag(GXMAP_OBJECT_HANDLE, DWORD);
    DWORD __stdcall GetPropertyFlag(GXMAP_OBJECT_HANDLE);
    void __stdcall EnablePick(GXMAP_OBJECT_HANDLE);
    void __stdcall DisablePick(GXMAP_OBJECT_HANDLE);
    void __stdcall EnableUpdateShading(GXMAP_OBJECT_HANDLE);
    void __stdcall DisableUpdateShading(GXMAP_OBJECT_HANDLE);
    void __stdcall LockTransform(GXMAP_OBJECT_HANDLE);
    void __stdcall UnLockTransform(GXMAP_OBJECT_HANDLE);
    BOOL __stdcall IsLockTransform(GXMAP_OBJECT_HANDLE);
    void __stdcall EnableSendShadow(GXMAP_OBJECT_HANDLE);
    void __stdcall DisableSendShadow(GXMAP_OBJECT_HANDLE);
    BOOL __stdcall IsInViewVolume(GXMAP_OBJECT_HANDLE);
    BOOL __stdcall IsCollisionWithScreenCoord(GXOBJECT_HANDLE, VECTOR3*, DWORD*, DWORD*, float*, POINT*, DWORD, DWORD);
    DWORD __stdcall GetFrameCount();
    BOOL __stdcall PreCreateLight(char*, DWORD);
    DWORD __stdcall PreLoadGXObject(char*);
    GXOBJECT_HANDLE __stdcall CreateGXObject(char*, GXSchedulePROC, void*, DWORD);
    GXLIGHT_HANDLE __stdcall CreateGXLight(LIGHT_DESC*, GXLightSchedulePROC, void*, DWORD, MATERIAL*, DWORD);
    GXTRIGGER_HANDLE __stdcall CreateGXEventTrigger(GXSchedulePROC, void*, DWORD);
    GXMAP_HANDLE __stdcall CreateGXMap(GXMapSchedulePROC, void*, DWORD);
    void __stdcall UnloadPreLoadedGXObject(GXOBJECT_HANDLE);
    void __stdcall UnloadAllPreLoadedGXObject(DWORD);
    BOOL __stdcall BeginBuildMap(DWORD);
    BOOL __stdcall InsertHFieldToGXMap(IHeightField*);
    BOOL __stdcall InsertStaticModelTOGXMap(I3DStaticModel*);
    BOOL __stdcall EndBuildMap(float, float);
    BOOL __stdcall RebuildMap(float, float);
    BOOL __stdcall GetWorldBoundingBox(MAABB*);
    DWORD __stdcall GetFramePerSec();
    void __stdcall SetFramePerSec(DWORD);
    void __stdcall GXLSetLightDesc(GXLIGHT_HANDLE, LIGHT_DESC*);
    void __stdcall GXLGetLightDesc(GXLIGHT_HANDLE, LIGHT_DESC*);
    void __stdcall GXLSetPosition(GXLIGHT_HANDLE, VECTOR3*);
    void __stdcall GXLGetPosition(GXLIGHT_HANDLE, VECTOR3*);
    void __stdcall GXLMovePosition(GXLIGHT_HANDLE, VECTOR3*);
    GXLIGHT_HANDLE __stdcall GXLGetLightWithScreenCoord(VECTOR3*, float*, POINT*, DWORD, DWORD);
    void __stdcall GXLDisableStaticShadow(GXLIGHT_HANDLE);
    void __stdcall GXLEnableStaticShadow(GXLIGHT_HANDLE);
    BOOL __stdcall GXLIsDisableStaticShadow(GXLIGHT_HANDLE);
    void __stdcall GXLEnableDynamicLight(GXLIGHT_HANDLE);
    void __stdcall GXLDisableDynamicLight(GXLIGHT_HANDLE);
    BOOL __stdcall GXLIsEnableDynamicLight(GXLIGHT_HANDLE);
    void __stdcall GXTSetPosition(GXTRIGGER_HANDLE, VECTOR3*);
    void __stdcall GXTSetScale(GXTRIGGER_HANDLE, VECTOR3*);
    void __stdcall GXTSetRotation(GXTRIGGER_HANDLE, VECTOR3*);
    void __stdcall GXTGetEventTriggerDesc(GXTRIGGER_HANDLE, EVENT_TRIGGER_DESC*);
    GXTRIGGER_HANDLE __stdcall GXTGetObjectWithScreenCoord(VECTOR3*, float*, POINT*, DWORD, DWORD);
    BOOL __stdcall GXMGetCollisionPointWithScreenCoord(DWORD*, VECTOR3*, float*, POINT*, DWORD);
    BOOL __stdcall GXMGetHFieldCollisionPointWithRay(VECTOR3*, float*, VECTOR3*, VECTOR3*);
    BOOL __stdcall GXMGetHFieldCollisionPointWithScreenCoord(VECTOR3*, float*, POINT*);
    BOOL __stdcall GXMGetHFieldHeight(float*, float, float);
    BOOL __stdcall GXMStaticShadeMap(DWORD, LIGHT_DESC*, DWORD, DWORD, SHADE_FUNC);
    void __stdcall GXMSetHFieldAlphaFlag(DWORD);
    void __stdcall GXMSetSTMAlphaFlag(DWORD);
    BOOL __stdcall SetSymbol(SYMBOL_TYPE, char*);
    void __stdcall SetRenderMode(DWORD);
    DWORD __stdcall GetRenderMode();
    VOID __stdcall SetPickingMode(DWORD);
    BOOL __stdcall DisableRenderAllStaticModels();
    BOOL __stdcall EnableRenderAllStaticModels();
    void __stdcall GXOSetBoundingVolume(GXOBJECT_HANDLE, BOUNDING_VOLUME*);
    DWORD __stdcall GetGXObjectsNum();
    GXOBJECT_HANDLE __stdcall GetGXObjectWithSeqIndex(DWORD);
    DWORD __stdcall GetGXLightsNum();
    GXLIGHT_HANDLE __stdcall GetGXLightWithSeqIndex(DWORD);
    DWORD __stdcall GetGXEventTriggersNum();
    GXTRIGGER_HANDLE __stdcall GetGXEventTriggerWithSeqIndex(DWORD);
    BOOL __stdcall LoadMapScript(char*, LOAD_CALLBACK_FUNC, DWORD);
    void __stdcall DeleteAllGXMapObjectsWitLoadMapScript();
    void __stdcall Render();
    BOOL __stdcall RenderCameraFrontObject();
    DWORD __stdcall Process();
    DWORD __stdcall Run(DWORD, GX_FUNC, GX_FUNC, DWORD);
    BOOL __stdcall SetCameraFitGXObject(GXOBJECT_HANDLE, float, float, float, DWORD);
    void __stdcall SetHFieldDetail(DWORD);
    BOOL __stdcall DeleteGXObject(GXOBJECT_HANDLE);
    BOOL __stdcall DeleteGXLight(GXLIGHT_HANDLE);
    BOOL __stdcall DeleteGXEventTrigger(GXTRIGGER_HANDLE);
    BOOL __stdcall DeleteGXMap(GXMAP_HANDLE);
    BOOL __stdcall DeleteAllGXObjects();
    BOOL __stdcall DeleteAllGXLights();
    BOOL __stdcall DeleteAllGXEventTriggers();
    BOOL __stdcall ImmDeleteGXObject(GXOBJECT_HANDLE);
    BOOL __stdcall ImmDeleteGXLight(GXLIGHT_HANDLE);
    BOOL __stdcall ImmDeleteGXEventTrigger(GXTRIGGER_HANDLE);
    BOOL __stdcall ImmDeleteGXDecal(GXDECAL_HANDLE);
    BOOL __stdcall DefDeleteGXObject(GXOBJECT_HANDLE);
    BOOL __stdcall DefDeleteGXLight(GXLIGHT_HANDLE);
    BOOL __stdcall DefDeleteGXEventTrigger(GXTRIGGER_HANDLE);
    BOOL __stdcall DefDeleteGXDecal(GXTRIGGER_HANDLE);
    GXDECAL_HANDLE __stdcall CreateGXDecal(DECAL_DESC*, GXDecalSchedulePROC, void*, DWORD);
    BOOL __stdcall DeleteGXDecal(GXDECAL_HANDLE);
    BOOL __stdcall GetMapReadCount(char*);
    BOOL __stdcall GXOInitializeIllusionEffect(GXOBJECT_HANDLE, DWORD, char*, void*, DWORD);
    void __stdcall GXOBeginIllusionEffect(GXOBJECT_HANDLE);
    void __stdcall GXOEndIllusionEffect(GXOBJECT_HANDLE);
    DWORD __stdcall GXOGetAttachedGXObjects(GXOBJECT_HANDLE, GXOBJECT_HANDLE*, DWORD);
    void __stdcall GXOSetScheduleProc(GXOBJECT_HANDLE, GXSchedulePROC);
    GXSchedulePROC __stdcall GXOGetScheduleProc(GXOBJECT_HANDLE);
    void __stdcall GXOSetEffectIndex(GXOBJECT_HANDLE, DWORD);
    DWORD __stdcall GXOGetEffectIndex(GXOBJECT_HANDLE);
    void __stdcall SetAfterInterpolation(AfterInterpolationCallBack);
    DWORD __stdcall GetCurrentGameFrame();
    ULONG __stdcall GXMGetStaticModel(I3DStaticModel**);
    ULONG __stdcall GXMGetHField(IHeightField**);
    void __stdcall GXODisableUnloadPreLoaded(GXOBJECT_HANDLE);
    void __stdcall GXOEnableUnloadPreLoaded(GXOBJECT_HANDLE);
    void __stdcall GXOGetLastVelocityAfterCollisionTest(GXOBJECT_HANDLE, VECTOR3*);
    void __stdcall GXOEnableScaleOfAttachedModel(GXOBJECT_HANDLE);
    void __stdcall GXODisableScaleOfAttachedModel(GXOBJECT_HANDLE);
    void __stdcall SetModelLODUsingMode(DWORD, DWORD);
    DWORD __stdcall GetModelLODUsingMode();
    DWORD __stdcall GetModelLodUsingLevel();
    MATRIX4 __stdcall GXOGetParentMatrix(GXOBJECT_HANDLE);
    BOOL __stdcall GXOIsCollisionMeshWithBoundingBox(GXOBJECT_HANDLE, VECTOR3*, DWORD*, DWORD*, float*, COLLISION_MESH_OBJECT_DESC*);
    BOOL __stdcall GXOIsCollisionMeshWithObjectBoundingBox(GXOBJECT_HANDLE, VECTOR3*, DWORD*, DWORD*, float*, GXOBJECT_HANDLE);
    BOOL __stdcall GXOIsCollisionBoungingBoxWithScreenCoord(GXOBJECT_HANDLE, VECTOR3*, VECTOR3*, POINT*, DWORD);
    DWORD __stdcall GXOGetModelNum(GXOBJECT_HANDLE);
    DWORD __stdcall GXOGetObjectNum(GXOBJECT_HANDLE, DWORD);
    BOOL __stdcall GXOGetCollisononObjectDesc(GXOBJECT_HANDLE, COLLISION_MESH_OBJECT_DESC*, DWORD, DWORD);
    BOOL __stdcall GXOGetCollisionModelDesc(GXOBJECT_HANDLE, COLLISION_MODEL_DESC*, DWORD);
    BOOL __stdcall GXOGetWorldMatrixByName(GXOBJECT_HANDLE, MATRIX4*, char*);

private:
    ULONG m_refCount;
    std::unique_ptr<RenderDevice> m_renderDevice;
    std::unique_ptr<TextureManager> m_textureManager;
    std::unique_ptr<ShaderManager> m_shaderManager;
    DWORD m_dwViewportIndex, m_dwRenderMode, m_dwPickingMode;
    DWORD m_dwFrameCount, m_dwGameFPS, m_dwTicksPerFrame;
};
