#!/usr/bin/env python3
"""
LUNA Plus Reborn — Item Model Table Generator
Scans converted model files + game database to generate ItemModelTable entries.
"""
import os
import sys
import re
import sqlite3
import argparse
from pathlib import Path

REBORN = Path(os.environ.get('LUNA_REBORN_ROOT', Path(__file__).parent.parent.parent))

def guess_bone(name):
    name_lower = name.lower()
    if 'head' in name_lower or 'hat' in name_lower or 'helm' in name_lower:
        return '"Bip01 Head"'
    if 'wing' in name_lower or 'back' in name_lower or 'cloak' in name_lower or 'cape' in name_lower:
        return '"Bip01 Spine2"'
    if 'weapon' in name_lower or 'sword' in name_lower or 'staff' in name_lower or 'bow' in name_lower or 'blade' in name_lower or 'axe' in name_lower or 'wand' in name_lower:
        return '"Bip01 R Hand"'
    if 'shield' in name_lower or 'arm' in name_lower or 'glove' in name_lower:
        return '"Bip01 L Hand"'
    if 'foot' in name_lower or 'boot' in name_lower or 'shoe' in name_lower or 'leg' in name_lower or 'pant' in name_lower:
        return '"Bip01 L Foot"'
    if 'body' in name_lower or 'chest' in name_lower or 'armor' in name_lower or 'torso' in name_lower or 'dress' in name_lower or 'coat' in name_lower:
        return '"Bip01 Spine1"'
    return '"Bip01 Spine2"'

def main():
    parser = argparse.ArgumentParser(description='Generate ItemModelTable from scanned assets')
    parser.add_argument('--mod-obj-dir', default=str(REBORN / 'assets_converted/mod_objs'), help='Scanned model directory')
    parser.add_argument('--models-dir', default=str(REBORN / 'assets/models'), help='Converted model directory')
    parser.add_argument('--db-path', default=str(REBORN / 'data/game_data.db'), help='Game database path')
    parser.add_argument('--output', default=str(REBORN / 'game/data/ItemModelTable_generated.hpp'), help='Output header path')
    parser.add_argument('--offset-id', type=int, default=900000, help='Starting item ID for unmatched models')
    args = parser.parse_args()

    # Scan model files
    model_files = []
    for ext in ('*.obj', '*.glb'):
        for d in (args.mod_obj_dir, args.models_dir):
            p = Path(d)
            if p.exists():
                model_files.extend(sorted(p.glob(ext)))

    if not model_files:
        print(f"No model files found in {args.mod_obj_dir} or {args.models_dir}")
        with open(args.output, 'w') as f:
            f.write('// Auto-generated by generate_item_models.py\n')
            f.write('#pragma once\n')
            f.write('// No models found — file is empty\n')
        print(f"Generated empty: {args.output}")
        return 0

    # Try to read item DB for mapping resource_id → item_id
    item_id_by_resource = {}
    item_names = {}
    conn = None
    try:
        if os.path.exists(args.db_path):
            conn = sqlite3.connect(args.db_path)
    except Exception:
        pass

    if conn:
        try:
            cursor = conn.cursor()
            cursor.execute("SELECT id, name, resource_id FROM item_templates WHERE resource_id > 0")
            for row in cursor.fetchall():
                item_id, name, resource_id = row
                item_id_by_resource[resource_id] = item_id
                item_names[item_id] = name
        except Exception as e:
            print(f"DB warning: {e}")
        conn.close()

    entries = []
    seen_ids = set()
    auto_id = args.offset_id

    for mf in model_files:
        stem = mf.stem.lower()
        rel = mf.relative_to(REBORN)
        rel_str = str(rel)

        # Extract numbers from filename to guess resource_id
        nums = re.findall(r'\d+', stem)
        matched_id = None
        for n in nums:
            n_int = int(n)
            if n_int in item_id_by_resource:
                matched_id = item_id_by_resource[n_int]
                break
            # Also try matching item_id directly
            if n_int >= 1000 and n_int in item_names:
                matched_id = n_int
                break

        if matched_id and matched_id not in seen_ids:
            seen_ids.add(matched_id)
            item_id = matched_id
        else:
            # Generate automatic ID — skip duplicates
            stem_clean = stem.replace('[r]_', '').replace('[', '').replace(']', '')
            if stem_clean in seen_ids:
                continue
            seen_ids.add(stem_clean)
            item_id = auto_id
            auto_id += 1

        bone = guess_bone(stem)
        entries.append((item_id, f'"{rel_str}"', bone))

    # Generate header
    lines = [
        '// Auto-generated by generate_item_models.py',
        '// DO NOT EDIT MANUALLY — re-run the script to update',
        '#pragma once',
        '#include <string>',
        '#include <unordered_map>',
        '',
        'namespace Luna {',
        '    inline std::unordered_map<uint32_t, ItemModelInfo> g_ItemModelsGenerated = {',
    ]

    for item_id, model_str, bone in entries[:5000]:
        lines.append(f'        {{{item_id}, {{{model_str}, {bone}}}}},')

    lines.extend([
        '    };',
        '}',
        '',
    ])

    out_dir = os.path.dirname(args.output)
    os.makedirs(out_dir, exist_ok=True)
    with open(args.output, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Generated {len(entries)} entries → {args.output}")
    return 0

if __name__ == '__main__':
    sys.exit(main())
