include "Types.fbs";
include "PacketType.fbs";

namespace luna.protocol;

table CharacterInfo {
    id: uint32;
    name: string;
    level: uint16;
    class: uint16;
    gender: uint8;
    map_id: uint16;
    position: Vec3;
    hp: uint32;
    max_hp: uint32;
    body_type: uint8;
    face_id: uint8;
    hair_id: uint8;
    weapon_id: uint32;
    dress_id: uint32;
    shoes_id: uint32;
    glove_id: uint32;
    job_grade: uint8;
    job1: uint8;
    job2: uint8;
    job3: uint8;
    job4: uint8;
    job5: uint8;
    job6: uint8;
    guild_name: string;
}

table CharacterListRequest {
    session_token: string;
}

table CharacterListResponse {
    characters: [CharacterInfo];
    max_slots: uint8;
}

table CreateCharacterRequest {
    session_token: string;
    name: string;
    class: uint16;
    gender: uint8;
    body_type: uint8;
    face_id: uint8;
    hair_id: uint8;
}

table CreateCharacterResponse {
    result: byte;
    character: CharacterInfo;
}

table DeleteCharacterRequest {
    session_token: string;
    character_id: uint32;
}

table DeleteCharacterResponse {
    result: byte;
}

table EnterWorldRequest {
    session_token: string;
    character_id: uint32;
}

table EnterWorldResponse {
    result: byte;
    map_id: uint16;
    position: Vec3;
    session_key: uint32;
}
